# handler paths are based off of the parent serverless.yml file location

list:
  handler: build/handlers/user-profile/list.handler
  events:
    - http: get /user-profiles

get:
  handler: build/handlers/user-profile/get.handler
  events:
    - http:
        method: get
        path: /user-profile/{id}
        integration: lambda
        request:
          template:
            # this can also be a ${file(template/path/reference)}
            application/json: '{ "id": "$input.params(\"id\")" }'
