# build the postgres image with the db create script in it
FROM postgres:12

# explicit
# override when creating starting the container
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres123

EXPOSE 5432